[package]
versioned_files = ["gleam.toml"]
changelog = "CHANGELOG.md"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Command"
command = "just clean build check test-all"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = 'git commit -m "chore: prepare release $version"'

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[[workflows.steps]]
type = "Command"
command = "just publish --yes"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[[workflows]]
name = "get-version"
help_text = "Get the current version of the project"

[[workflows.steps]]
type = "Command"
command = 'echo "$version"'

[github]
owner = "han-tyumi"
repo = "gossamer"
