[settings]
lockfile = true

[tools]
bun = "1.3.14"
deno = "2.9.1"
erlang = "29.0.3"
"aqua:gleam-lang/gleam" = "1.17.0"
"aqua:casey/just" = "1.55.1"
"aqua:evilmartians/lefthook" = "2.1.9"
node = "26.4.0"
"github:erlang/rebar3" = "3.27.0"
"aqua:watchexec/watchexec" = "2.5.1"
